config/routes.rb
Rails.application.routes.draw do

  get 'sanpham1/index'
  get 'searchsp/index'
 resources :sanpham
  resources :tiplamdep
  resources :instruments
  resources :dichvu
	devise_for :users, controller: {
    registrations: 'registrations'
  }

   resources :searchsp, only: [:index] do
    collection do 
      get 'results'
    end
  end
  root 'instruments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    before_destroy :not_refereced_by_any_line_item
    mount_uploader :image, ImageUploader
    serialize :image,JSON
    has_many :line_items
    belongs_to :user, optional: true
    validates :title, :brand, :price, :model, presence: true
    validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud."}
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
    validates :price, numericality: { only_integer: true }
    

    BRAND = %w{ Mỹ Pháp Đức }
    FINISH = %w{ 30ml 100ml 400ml }
    CONDITION = %w{ Normal Double Triple }

    private

    def not_refereced_by_any_line_item
      
        errors.add(:base, "Chi tiết")
        throw :abort
      end
   
  
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
end

app/models/sanpham1.rb
class Sanpham1 < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dichvu_controller.rb
class DichvuController < ApplicationController
  def index
  end
end

app/controllers/sanpham1_controller.rb
class Sanpham1Controller < ApplicationController
  def index
  	 @sanpham1 = Sanpham1.all
  end
end

app/controllers/sanpham_controller.rb
class SanphamController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
    end

 
end

app/controllers/searchsp_controller.rb
class SearchspController < ApplicationController
    def index
    end

    def results
       
         @sanpham1 = Sanpham1.where('ten LIKE ?',"%#{params[:q]}%")
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/tiplamdep_controller.rb
class TiplamdepController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dichvu_helper.rb
module DichvuHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
    def instrument_auth(instrument)
        user_signed_in? && current_user.id == instrument.user_id
    end
end

app/helpers/sanpham1_helper.rb
module Sanpham1Helper
end

app/helpers/sanpham_helper.rb
module SanphamHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchsp_helper.rb
module SearchspHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tiplamdep_helper.rb
module TiplamdepHelper
end

app/views/searchsp/index.html.erb
<%= form_tag(results_searchsp_index_path, method:"get",  style:'padding:22px;', class:'form-inline my-2 my-lg-0') do%>
  
  <%=text_field_tag(:q, "", placeholder:'Tìm trong trang', style:'border-radius: 15px', class:'form-control mr-sm-2')  %>
  <%= submit_tag("Tìm kiếm", class:'btn btn-outline-success my-2 my-sm-0' )  %>
<% end %>

app/views/searchsp/results.html.erb
<h2 >Kết quả tìm kiếm: <%= @sanpham1.size %></h2>
    <% if @sanpham1.empty? %>
<p>Không tìm thấy kết quả</p>
<% else %>
<ul>
<% @sanpham1.all.each do |sanpham1|%>
<li>
	<div style="width: 300px;height: 280px">
<p><%= image_tag sanpham1.image %></p>
	</div>		<br>						
<p style="font-size: 20px;font-weight: 500;"><%= sanpham1.ten %></p>
</li>
<% end %>
</ul>
<% end %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>

app/views/tiplamdep/index.html.erb
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<link rel="stylesheet" href="assets/stylesheets/css/base.css">
<link rel="stylesheet" href="assets/stylesheets/css/skeleton.css">
<link rel="stylesheet" href="assets/stylesheets/css/screen.css">
<link rel="stylesheet" href="assets/stylesheets/css/prettyPhoto.css" type="text/css" media="screen" />
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>

<div class="container">  <br>


<div class="w3-content w3-section w3-center" style="max-width:100%"> 
  <img class="mySlides" src="https://thanhtamspa.vn/wp-content/uploads/2020/05/u-1400x545.jpg" style="width:100%">
  <img class="mySlides" src="https://thanhtamspa.vn/wp-content/uploads/2020/05/t-1400x545.jpg" style="width:100%">
  <img class="mySlides" src="https://tambeautyclinic.vn/wp-content/uploads/2021/04/Tam-Banner-website-BP210420.jpg" style="width:100%">
 
</div>

<script>
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}    
  x[myIndex-1].style.display = "block";  
  setTimeout(carousel, 3000); // Change image every 2 seconds
}
</script>

</div> <br>
<div class="breadcrumbs">
  <div class="container">
    <header>
      <h3>Makeup</h3>
      <p>--- Giúp các bạn tìm phong cách makeup cho bản thân ---</p>
    </header>
  </div>
  <!-- container ends here -->
  <hr class="separator1">
</div>
<!-- breadcrumbs ends here --> 
<!-- Blog ==================================================
================================================== -->
<div class="container" style="margin-left: 190px">
  <div class="ten columns alpha">
    <article class="post1">
      <h3>Makeup tông cam đào</h3>
      <a href="images/flexslider/m1.jpg" class="prettyPhoto[gal]"><iframe width="560" height="315" src="https://www.youtube.com/embed/xYiK_K-kX-Q" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></a>
      <div class="entry-date">
        <div class="number">20/06/2020</div>
      </div>
      <p>Make up Hàn Quốc tone cam đào đang là phong cách trang điểm nhẹ nhàng mà rất nhiều cô nàng quan tâm, yêu thích trong thời gian qua. Phong cách trang điểm sương sương này sẽ khiến cho những cô nàng của chúng ta trở nên ngọt ngào, mong manh và vô cùng thu hút người đối diện. Vậy bạn đã biết cách thực hiện chưa? Tham khảo ngay thôi nào!</p>
     
    <article class="post">
      <h3>Makeup đơn giản vào ngày hè</h3>
      <a href="images/flexslider/2.jpg" class="prettyPhoto[gal]"><iframe width="560" height="315" src="https://www.youtube.com/embed/fae8EOutEqg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></a>
      <div class="entry-date">
        <div class="number">20/06/2020</div>
      </div>
      <p>Hôm nay mình muốn đưa đến các bạn cách trang điểm tự nhiên nhất. Chúng ta vẫn sử dụng son phấn nhưng quan điểm là thật tự nhiên, tươi tắn, không để lại quá nhiều dấu vết của việc trang điểm, nó giúp bạn trở nên tươi mát và tinh khiết. Không cần phải đánh màu mắt hay kẻ eyeliner, bạn vẫn có thể trở nên xinh tươi hơn với vài bước cơ bản, rất đơn giản và dễ thực hiện. Hãy cùng thử nghiệm ngay nhé!</p>
    <article class="post">
      <h3>Trang điểm mắt phong cách ngọt ngào</h3>
      <a href="images/flexslider/2.jpg" class="prettyPhoto[gal]"><iframe width="560" height="315" src="https://www.youtube.com/embed/tZoDWhGJWFI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></a>
      <div class="entry-date">
        <div class="number">20/06/2020</div>
      </div>
      <p>Hôm nay mình sẽ sử dụng bảng màu mắt Clio 04, là sự kết hợp hoàn hảo giữa 2 tone hồng đất và cam đất. Để hướng dẫn các bạn cách trang điểm mắt thành một cô gái ngọt ngào, dễ thương nhưng vẫn cá tính nhé. Let's go!</p>
  </div>
  <!-- ten columns ends here -->
 
  <aside class="six columns omega shadow1" style="margin-left:100px" >
    <section class="recentnews">
      <h4 class="sidebarheader">Mẹo nhỏ</h4>
      <ul class="tabs">
        <li><a class="active" href="#trends">Đánh Nền</a></li>
        <li><a class="" href="#fashion">Trang điểm mắt</a></li>
        <li><a class="" href="#shows">Tô Son</a></li>
      </ul>
      <ul class="tabs-content">
        <li class="active" id="trends">
          <p>Kem nền là loại kem không thể thiếu trong trang điểm. Nhưng để lựa chọn một loại phấn phù hợp với da và sử dụng nó đúng cách thật không dễ dàng. Nhiều người khi đánh phấn nền thường miết rất mạnh lên mặt để phấn bám được lâu và bền. Thực tế cách làm này khiến phấn trượt đi, không ăn vào da và làm hỏng cấu trúc hạt phấn khiến nó nhanh chảy. Hãy nghiên cứu cách sử dụng phấn nền bên dưới để tạo ra sự mịn màng cho gương mặt khi trang điểm bạn nhé.</p>
        </li>
        <li id="fashion">
          <p>Thật ra cách đánh mắt của con gái Hàn rất đơn giản, họ thường tập trung vào phần đuôi mắt để tạo điểm nhấn, làm mắt trông sâu và to hơn. Chúng ta cùng tham khảo qua cách trang điểm của họ nhé!</p>
          <p>- Bước 1: Phủ một lớp kem lót cho mắt, để màu mắt lên chuẩn hơn.</p>
          <p>- Bước 2: Dùng cọ đánh một lớp màu nền cho cả bầu mắt và một ít phủ dưới bọng mắt.</p>
          <p>- Bước 3: Tạo điểm nhấn ở đuôi mắt bằng một gam màu tương tự nhưng màu đậm hơn.</p>
          <p>- Bước 4: Kẻ một đường mảnh eyeliner cho mắt (chú ý màu eyeliner càng gần màu tóc thì càng tốt).</p>
        </li>
        <li id="shows">
          <p>Có người ví tô son môi là một nghệ thuật và không phải cũng có thể trở thành nghệ sĩ. Có những cách tô son nhất định mà hầu hết chị em không được biết đến, hoặc tự ý rút ngắn làm giảm vẻ đẹp của đôi môi. Với những bạn thực sự muốn biết cách trang điểm hợp lý cho đôi môi thì bài viết này là dành cho các bạn.</p>
          <p>- Tẩy da chết cho môi đúng cách</p>
          <p>- Thoa son dưỡng và kem lót</p>
        </li>
      </ul>
    </section>
    <!--end recent news-->
    <section class="latestphotos">
      <h4 class="sidebarheader">Sản phẩm đề cử</h4>
      <div class="one_half"> <%= image_tag("images/skincare/sanpham1.jpg")%> </div>
      <div class="one_half lastcolumn"> <%= image_tag("images/skincare/sanpham1.jpg")%>  </div>
      <div class="one_half"> <%= image_tag("images/skincare/sanpham1.jpg")%>  </div>
      <div class="one_half lastcolumn"> <%= image_tag("images/skincare/sanpham1.jpg")%> </div>
    </section>
    <!--end latestphotos-->
    <!--end categories--> 
  </aside>

  <!--end six columns--> 
</div>
        <hr class="separator2">
<div class="socialsblock">
  <div class="container socialize">
    <h3>Contact with us!</h3>
    <section class="socials">
      <ul class="socials">
        <li><a href="#"><%= image_tag("images/socials/twitter.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/facebook.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/google+.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/linkedin.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/youtube.png")%></a></li>
      </ul>
    </section>
  </div>
  
</div>
<div class="footer"style="background: pink">
  <div class="container" >
    <!-- four columns ends here -->
    <div class="one_fourth">
      <h3>Archive</h3>
      <ul>
        <li><a href="#" class="">July 2020</a></li>
        <li><a href="#" class="">Juny 2020</a></li>
        <li><a href="#" class="">May 2020</a></li>
        <li><a href="#" class="">April 2020</a></li>
        <li><a href="#" class="">March 2020</a></li>
      </ul>
    </div>
    <!-- four columns ends here -->
    <!-- four columns ends here --> 
  </div>
  <!-- container ends here --> 
</div>
<!-- footer ends here --> 
<!-- Copyright ==================================================
================================================== -->
<div id="copyright">
  <div class="container">
    <p class="copyright">&copy; Copyright 2020. by <a href="#" rel="nofollow">Nhưt,Tien, May and Vi studio</a></p>
  </div>
  <!-- container ends here --> 
</div>
</script>

<script src="assets/stylesheets/js/jquery-1.8.0.min.js" type="text/javascript"></script> 
<!-- Main js files --> 
<script src="assets/stylesheets/js/screen.js" type="text/javascript"></script> 
<!-- Tabs --> 
<script src="assets/stylesheets/js/tabs.js" type="text/javascript"></script> 
<!-- Include prettyPhoto --> 
<script src="assets/stylesheets/js/jquery.prettyPhoto.js" type="text/javascript"></script> 
<!-- Include Superfish --> 
<script src="assets/stylesheets/js/superfish.js" type="text/javascript"></script> 
<script src="assets/stylesheets/js/hoverIntent.js" type="text/javascript"></script> 
<!-- Flexslider --> 
<script src="assets/stylesheets/js/jquery.flexslider-min.js" type="text/javascript"></script> 
<!-- Modernizr --> 
<script type="assets/stylesheets/text/javascript" src="js/modernizr.custom.29473.js"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
    AOS.init();
</script>