config/routes.rb
Rails.application.routes.draw do

  get 'sanpham1/index'
  get 'searchsp/index'
 resources :sanpham
  resources :tiplamdep
  resources :instruments
  resources :dichvu
	devise_for :users, controller: {
    registrations: 'registrations'
  }

   resources :searchsp, only: [:index] do
    collection do 
      get 'results'
    end
  end
  root 'instruments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    before_destroy :not_refereced_by_any_line_item
    mount_uploader :image, ImageUploader
    serialize :image,JSON
    has_many :line_items
    belongs_to :user, optional: true
    validates :title, :brand, :price, :model, presence: true
    validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud."}
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
    validates :price, numericality: { only_integer: true }
    

    BRAND = %w{ Mỹ Pháp Đức }
    FINISH = %w{ 30ml 100ml 400ml }
    CONDITION = %w{ Normal Double Triple }

    private

    def not_refereced_by_any_line_item
      
        errors.add(:base, "Chi tiết")
        throw :abort
      end
   
  
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
end

app/models/sanpham1.rb
class Sanpham1 < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dichvu_controller.rb
class DichvuController < ApplicationController
  def index
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all.order("created_at desc")
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = current_user.instruments.build
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = current_user.instruments.build(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Đã thêm sản phẩm thành công' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end 
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Cập nhật thành công!' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Đã xóa thành công!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)
    end
end

app/controllers/sanpham1_controller.rb
class Sanpham1Controller < ApplicationController
  def index
  	 @sanpham1 = Sanpham1.all
  end
end

app/controllers/sanpham_controller.rb
class SanphamController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
    end

 
end

app/controllers/searchsp_controller.rb
class SearchspController < ApplicationController
    def index
    end

    def results
       
         @sanpham1 = Sanpham1.where('ten LIKE ?',"%#{params[:q]}%")
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/tiplamdep_controller.rb
class TiplamdepController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dichvu_helper.rb
module DichvuHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
    def instrument_auth(instrument)
        user_signed_in? && current_user.id == instrument.user_id
    end
end

app/helpers/sanpham1_helper.rb
module Sanpham1Helper
end

app/helpers/sanpham_helper.rb
module SanphamHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchsp_helper.rb
module SearchspHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tiplamdep_helper.rb
module TiplamdepHelper
end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">
<style>
form input {
  margin:15px 0;
  padding:20px 15px;
  width:100%;
  outline:none;
  border:1px solid #bbb;
  border-radius:20px;
  display:inline-block;
  
}
</style>
    <%= simple_form_for @instrument, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-4">
            <div class="control">
            <label class="label">Tên sản phẩm</label>
              <%= f.input_field :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column is-4">
            <div class="control">
            <label class="label">Giá sản phẩm</label>
              <%= f.input_field :price, required: true, input_html: { class:"input", maxlength: 11  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div><br>
           <div class="field column is-4">
          <div class="control">
            <label class="label">Mô tả:</label>
             <%= f.input_field :description, required: true, input_html: { class:"textarea " }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>
        </div>
        <div class="field column is-4">
            <div class="control">
            <label class="label">Loại sản phẩm</label>
              <%= f.input_field :model , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Chọn thương hiệu</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Instrument::BRAND, prompt: "Chọn thương hiệu" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Chọn size sản phẩm</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Instrument::FINISH, prompt: "Chọn size sản phẩm" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Tùy chọn khác</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Instrument::CONDITION, prompt: "Thêm sirum" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Thêm ảnh</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">chọn ảnh</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />
       <div class="columns">

          <div class="field column is-10">
            <div class="control">
            <%=  f.button :submit, "Submit", class: 'button is-dark' %></div>
            
            </div>
          </div>

          <div class="field column is-4">
            <div class="control">
            <%= link_to 'Hủy bỏ', instruments_path, class:'button is-light' %>
           </div>
          </div>
          
        </div>
       

      <% end %>
  </div>
</div>

app/views/instruments/edit.html.erb
<% content_for :header do %>
<section class="hero ">
  <div class="hero-body">
    <div class="container">
      <h2 style="color: #bf005f">
       <B> SỬA SẢN PHẨM </B>
      </h2>
    </div>
  </div>
</section>
<% end %>
<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
  <!-- CSS only -->


<!-- Favicons ==================================================
================================================== -->



<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<link rel="stylesheet" href="assets/stylesheets/css/base.css">
<link rel="stylesheet" href="assets/stylesheets/css/skeleton.css">
<link rel="stylesheet" href="assets/stylesheets/css/screen.css">
<link rel="stylesheet" href="assets/stylesheets/css/prettyPhoto.css" type="text/css" media="screen" />
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
 <div class="container">  <br>


<div class="w3-content w3-section w3-center" style="max-width:100%"> 
  <img class="mySlides" src="https://thanhtamspa.vn/wp-content/uploads/2020/05/u-1400x545.jpg" style="width:100%">
  <img class="mySlides" src="https://thanhtamspa.vn/wp-content/uploads/2020/05/t-1400x545.jpg" style="width:100%">
  <img class="mySlides" src="https://tambeautyclinic.vn/wp-content/uploads/2021/04/Tam-Banner-website-BP210420.jpg" style="width:100%">
 
</div>

<script>
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}    
  x[myIndex-1].style.display = "block";  
  setTimeout(carousel, 3000); // Change image every 2 seconds
}
</script>

</div> <br>
<div class="infobox">
  <div class="container info">
    <header>
      <h1>BEAUTIFUL!</h1>
      <p class="infop">- Beauty is power,  a smile is its sword -</p>
    </header>
    <hr class="separator">
  </div>
  <!-- container ends here --> 
</div>
<!-- infobox ends here --> 
<!--Latest Photos ==================================================
================================================== -->
<div class="container latest">
  <div class="one_third">
    <figure class="shadow"><a href="#" class="thumb">
      <%= image_tag("images/skincare/nen1.jpg")%>
    </a>
      <figcaption> <a href="#">
        <h3 class="heading">Quy Trình</h3>
        </a>
        <p class="bioquote">Các bước chăm sóc da phù hợp với nhu cầu, thời tiết và loại da.</p>
      </figcaption>
    </figure>
  </div>
  <!-- one_third ends here -->
  <div class="one_third">
    <figure class="shadow"><a href="#" class="thumb"><%= image_tag("images/skincare/nen2.jpg")%></a>
      <figcaption> <a href="#">
        <h3 class="heading">Sản Phẩm</h3>
        </a>
        <p class="bioquote">Lựa chọn đúng sản phẩm để giải quyết vấn đề của làn da.</p>
      </figcaption>
    </figure>
  </div>
  <!-- one_third ends here -->
  <div class="one_third lastcolumn">
    <figure class="shadow"><a href="#" class="thumb"><%= image_tag("images/skincare/nen2.png")%></a>
      <figcaption> <a href="#">
        <h3 class="heading">Trang Điểm</h3>
        </a>
        <p class="bioquote">Giúp bạn luôn tự tin, rạng rỡ trong mọi tình huống.</p>
      </figcaption>
    </figure>
  </div>
  <!-- one_third ends here -->
</div>
<!-- end container --> 
<!--Heading Box ==================================================
================================================== -->
<div class="headingblock">
  <div class="container heading">
    <header>
      <h2>BEAUTY FOR YOU!</h2>
      <p>- Everything has beauty, but not everyone sees it -</p>
    </header>
  </div>
  <!-- container ends here -->
  <hr class="separator1">
</div>
<!-- headingblock ends here --> 
<!-- Latest News & Faq ==================================================
================================================== -->






<div class="container latest">
  <div class="two_third">
    <div class="accordion-trigger">
      <h3>Sản phẩm cho mùa hè</h3>
    </div>
    <div class="accordion-container">
      <div class="one_third"> <%= image_tag("images/skincare/m1.jpg")%> </div>
      <!--end one_third-->
      <div class="one_third"> <%= image_tag("images/skincare/m2.png")%> </div>
      <!--end one_third-->
      <div class="one_third lastcolumn"> <%= image_tag("images/skincare/m3.jpg")%> </div>
      <p align="justify">Với thời tiết như thế này mà bôi các loại mỹ phẩm lên mặt thì cảm giác thật không thoải mái chút nào phải không các bạn? Tuy nhiên thời tiết này rất dễ làm cho da bị các tổn thương như cháy nắng, thâm nám, khô da v.v nên việc chăm sóc và dưỡng da cẩn thận là vô cùng quan trọng. Vì vậy tiêu chí lựa chọn sản phẩm cho mùa hè này là thẩm thấu nhanh, an toàn và không gây bí da.</p>
      <!--end one_third-->
      <hr class="separator1">
    </div>
    <div class="accordion-trigger">
      <h3>Xu hướng makeup</h3>
    </div>
    <div class="accordion-container">
      <div class="one_half">
        <div class="video-holder">
          <div class="video-container">
            <iframe title="YouTube video player" class="youtube-player" src="https://www.youtube.com/embed/HQSLsaQGEZ0"></iframe>
          </div>
          <!--video-container ends here--> 
        </div>
        <!--video-holder ends here--> 
      </div>
      <!--end one_half-->
      <div class="one_half lastcolumn">
        <div class="video-holder">
          <div class="video-container">
            <iframe title="YouTube video player" class="youtube-player" src="https://www.youtube.com/embed/NxLH_d957OY"></iframe>
          </div>
          <!--video-container ends here--> 
        </div>
        <!--video-holder ends here--> 
      </div>
      <!--end one_half-->
      <p>Bước sang năm 2020, một gương mặt đánh phấn nhẹ với má ửng hồng mềm mại và đầy ngọt ngào sẽ được phái đẹp chú ý và ưu ái. </p>
      <hr class="separator1">
    </div>
    
    <div class="accordion-trigger">
      <h3>11 thói quen giúp da bạn luôn rạng rỡ</h3>
    </div>
    <div class="accordion-container">
      <p>- Uống 6-8 ly nước một ngày (tương đương với 2 lít nước)</p>
      <p>- Tập thể dục căng da mặt</p>
      <p>- Nói không với đường</p>
      <p>- Ngủ trước nửa đêm</p>
      <p>- Bôi kem chống nắng đều đặn</p>
      <p>- Tẩy da chết và dưỡng ẩm</p>
      <p>- Ăn nhiều rau củ</p>
      <p>- Xông hơi đều đặn</p>
      <p>- Nghiêm khắc với khói thuốc</p>
      <p>- Dùng mĩ phẩm khoáng chất</p>
      <p>- Không sờ tay lên mặt</p>
      <hr class="separator1">
      <!-- ENDS Accordions --> 
    </div>
  </div>
  <!-- two_third ends here -->
  <div class="one_third lastcolumn">
    <h3>Bài viết Tiêu Biểu</h3>
    <article>
      <p>Makeup tông cam đào, ngọt ngào, rạng rỡ.</p>
      <p class="quote" align="justify">Phong cách trang điểm màu đào thiên về sự nhẹ nhàng, mềm mại và vẫn nổi bật sắc sảo, đề cao những đường nét tự nhiên, hài hòa.</p>
      <a href="#" title="">&rarr; More +</a></article>
    <hr class="separator1">
    <article>
      <p>Cảm nhận khi sử dụng The ordinay niacinamine 10% + zinc 1%</p>
      <p class="quote" align="justify">Niacinamide được biết đến như một dẫn xuất của vitamin B3, theo như Na tìm hiểu thì em này khả năng gây kích ứng da rất thấp, nên phần lớn bạn nào da nhạy cảm vẫn dùng được...</p>
      <a href="review1.html" title="">&rarr; More +</a></article>
    <hr class="separator1">
    <article>
      <p>Quy Trình 10 Bước Dưỡng Da Ban Đêm Của Người Hàn Quốc</p>
      <p class="quote">Làn da trắng sứ như có 1 lớp nước bao phủ của các cô gái Hàn Quốc là niềm mơ ước của không ít phụ nữ Á Châu. Bạn đừng ngạc nhiên khi nghe ai đó nói rằng phụ nữ Hàn có đến 10 bước dưỡng da mỗi sáng và tối, thậm chí còn hơn cả thế. Bạn nghĩ rằng các cô gái xứ lạnh được tự nhiên ưu ái cho làn da đẹp từ bé đến lớn sao?</p>
      <a href="#" title="">&rarr; More +</a></article>
  </div>
  <!-- one_third ends here --> 
</div>
<center><h2 style="font-size: 40PX">SẢN PHẨM BẠN ĐÃ THÊM </h2></center>
<div class="instrument-index-grid pt4">
  <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb ">
       
      </div>

<% if instrument.condition?%>
<div class="condition">
  <span class="tag is-dark"><%= instrument.condition %></span>
</div>
<% end %>
    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      <p class="has-text-gray fg pt1">Người bán: <%=(instrument.user.name) %></p>
      
      <p class="f3 fw6 has-text-right pt2 price"><%=(instrument.price) %> VNĐ</p>

      <% if instrument_path(instrument) %>
         <%= link_to 'Sửa', edit_instrument_path(instrument), class: "button is-small" %>
         <%= link_to 'Xóa', instrument, method: :delete, data: { confirm: "Bạn có chắc sẽ xóa sản phẩm này?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div><br><br><hr>
<br>

<%= link_to 'MỜI BẠN NHẬP THÔNG TIN SẢN PHẨM!', new_instrument_path %>
<hr class="separator2">
<div class="socialsblock">
  <div class="container socialize">
    <h3>Contact with us!</h3>
    <section class="socials">
      <ul class="socials">
        <li><a href="#"><%= image_tag("images/socials/twitter.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/facebook.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/google+.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/linkedin.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/youtube.png")%></a></li>
      </ul>
    </section>
  </div>
  
</div>
<div class="footer"style="background: pink">
  <div class="container" >
    <!-- four columns ends here -->
    <div class="one_fourth">
      <h3>Archive</h3>
      <ul>
        <li><a href="#" class="">July 2020</a></li>
        <li><a href="#" class="">Juny 2020</a></li>
        <li><a href="#" class="">May 2020</a></li>
        <li><a href="#" class="">April 2020</a></li>
        <li><a href="#" class="">March 2020</a></li>
      </ul>
    </div>
    <!-- four columns ends here -->
    <!-- four columns ends here --> 
  </div>
  <!-- container ends here --> 
</div>
<!-- footer ends here --> 
<!-- Copyright ==================================================
================================================== -->
<div id="copyright">
  <div class="container">
    <p class="copyright">&copy; Copyright 2020. by <a href="#" rel="nofollow">Nhưt,Tien, May and Vi studio</a></p>
  </div>
  <!-- container ends here --> 
</div>
<script src="assets/stylesheets/js/jquery-1.8.0.min.js" type="text/javascript"></script> 
<!-- Main js files --> 
<script src="assets/stylesheets/js/screen.js" type="text/javascript"></script> 
<!-- Tabs --> 
<script src="assets/stylesheets/js/tabs.js" type="text/javascript"></script> 
<!-- Include prettyPhoto --> 
<script src="assets/stylesheets/js/jquery.prettyPhoto.js" type="text/javascript"></script> 
<!-- Include Superfish --> 
<script src="assets/stylesheets/js/superfish.js" type="text/javascript"></script> 
<script src="assets/stylesheets/js/hoverIntent.js" type="text/javascript"></script> 
<!-- Flexslider --> 
<script src="assets/stylesheets/js/jquery.flexslider-min.js" type="text/javascript"></script> 
<!-- Modernizr --> 
<script type="assets/stylesheets/text/javascript" src="js/modernizr.custom.29473.js"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
    AOS.init();
</script>

app/views/instruments/new.html.erb
<% content_for :header do %>
<section class="hero k">
  <div class="hero-body">
    <div class="container">
      <h2 style="color: #bf005f">
         Nhập thông tin thêm sản phẩm mới
      </h2>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrument.title %></h1>

      <ul class="pv1">
        
        
      </ul>

      <div class="feature-image">
       
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Mô tả:</h3>
      <%= @instrument.description %>



      <table class="table is-narrow">
        <% if @instrument.condition %>
        <tr>
          <td class="has-text-weight-bold"></td>
          <td><%#= @instrument.condition %></td>
        </tr>
        <% end %>
        <% if @instrument.finish %>
          <tr>
            <td class="has-text-weight-bold">size mỹ phẩm </td>
            <td><%= @instrument.finish %></td>
          </tr>
        <% end %>
        <% if @instrument.brand %>
          <tr>
            <td class="has-text-weight-bold">Thương Hiệu sản phẩm :</td>
            <td><%= @instrument.brand %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Số lượng sản phẩm :</td>
          <td><%= @instrument.condition %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-5 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%=(@instrument.price) %> VNĐ</h4>
        
        <p class="has-text-centered mb3">Người bán:<%= (@instrument.user.email) %></p>

        
      </div>
    </div>
  </div>

  <% if instrument_path(@instrument) %>
    <%= link_to ' Sửa', edit_instrument_path(@instrument), class: 'button' %>
  <% end %>
</section>

app/views/sanpham1/index.html.erb
 
  <style type="text/css">
  	
.img image_tag{
	widows: 200px;background-position: all;
	height: 150px;
  
}
</style>

<h1 align="center">DANH SÁCH SẢN PHẨM</h1>
		
<table style="margin-left: 50px">
              <tr>
              	<% Sanpham1.limit(4).each do |sanpham1|%>
                <td>
                	
                   <div class="card" style="width: 20rem; margin-top: 30px; border:  pink solid 2px">
                  	<p ><%= image_tag sanpham1.image %></p>
                  <p style="border:  pink solid 1px;text-align: center;font-weight: bold;color: #CC3366;font-size: 20px "><%= sanpham1.ten %>
									</p>
                   
                  <div class="card-body" style="font-size:15px">
                  	Review:
                    <%= sanpham1.review %>
                  </div>
                </div>
               	
                </td>
                 <% end %>
               
                </tr>
  </table><br><br>

   <table style="margin-left: 50px">
              <tr>
              	<% Sanpham1.limit(4).offset(4).each do |sanpham1|%>
                <td style="margin-right: 50px">
                	
                  <div class="card" style="width: 20rem; margin-top: 30px; border:  pink solid 2px">
                    <div style="width: 300px;height: 280px">
                  	<p class="img"><%= image_tag sanpham1.image %></p>
                  </div>
                  <p style="text-align: center;font-weight: bold;color: #CC3366;font-size: 20px"><%= sanpham1.ten %>
									</p>
                   
                  <div class="card-body" style="font-size:15px">
                  	Review:
                    <%= sanpham1.review %>
                  </div>
                </div>
               	
                </td>
                 <% end %>
               
                </tr>
  </table><br><br>
  <table style="margin-left: 50px">
             <tr>
              	<% Sanpham1.limit(4).offset(8).each do |sanpham1|%>
                <td style="margin-right: 50px">
                	
                  <div class="card" style="width: 20rem; margin-top: 30px; border:  pink solid 2px">
                  	<div style="width: 300px;height: 280px">
                  	<p class="img"><%= image_tag sanpham1.image %></p>
                  </div>
                  <p style="border:  pink solid 1px;text-align: center;font-weight: bold;color: #CC3366;font-size: 20px"><%= sanpham1.ten %>
									</p>
                   
                  <div class="card-body" style="font-size:15px">
                  	Review:
                    <%= sanpham1.review %>
                  </div>
                </div>
               	
                </td>
                 <% end %>
               
                </tr>
  </table><br><br>
    <hr class="separator2">
<div class="socialsblock">
  <div class="container socialize">
    <h3>Contact with us!</h3>
    <section class="socials">
      <ul class="socials">
        <li><a href="#"><%= image_tag("images/socials/twitter.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/facebook.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/google+.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/linkedin.png")%></a></li>
        <li><a href="#"><%= image_tag("images/socials/youtube.png")%></a></li>
      </ul>
    </section>
  </div>
  
</div>
<div class="footer"style="background: pink">
  <div class="container" >
    <!-- four columns ends here -->
    <div class="one_fourth">
      <h3>Archive</h3>
      <ul>
        <li><a href="#" class="">July 2020</a></li>
        <li><a href="#" class="">Juny 2020</a></li>
        <li><a href="#" class="">May 2020</a></li>
        <li><a href="#" class="">April 2020</a></li>
        <li><a href="#" class="">March 2020</a></li>
      </ul>
    </div>
    <!-- four columns ends here -->
    <!-- four columns ends here --> 
  </div>
  <!-- container ends here --> 
</div>
<!-- footer ends here --> 
<!-- Copyright ==================================================
================================================== -->
<div id="copyright">
  <div class="container">
    <p class="copyright">&copy; Copyright 2020. by <a href="#" rel="nofollow">Nhưt,Tien, May and Vi studio</a></p>
  </div>
  <!-- container ends here --> 
</div>
               